// GENERATED by scripts/sync-theme.mjs from the Style-Guide palette/colors.json.
// Do not edit by hand — run `npm run sync-theme`.

export const tokens = {
  "version": "0.2.0",
  "categorical": [
    {
      "key": "blue",
      "name": "Blue",
      "position": 1,
      "base": "#0072B2",
      "light": "#58A3E7"
    },
    {
      "key": "amber",
      "name": "Amber",
      "position": 2,
      "base": "#E69F00",
      "light": "#FFC63D"
    },
    {
      "key": "violet",
      "name": "Violet",
      "position": 3,
      "base": "#8856BF",
      "light": "#BC85F4"
    },
    {
      "key": "green",
      "name": "Green",
      "position": 4,
      "base": "#2A8B3A",
      "light": "#70CD76"
    },
    {
      "key": "red",
      "name": "Red",
      "position": 5,
      "base": "#B8302C",
      "light": "#FF7062"
    },
    {
      "key": "rose",
      "name": "Rose",
      "position": 6,
      "base": "#CC79A7",
      "light": "#FFBAE9"
    },
    {
      "key": "russet",
      "name": "Russet",
      "position": 7,
      "base": "#7A5230",
      "light": "#A77A56"
    }
  ],
  "scales": {
    "blue": {
      "50": "#95DAFF",
      "100": "#77BEFF",
      "200": "#58A3E7",
      "300": "#3689CB",
      "400": "#0070AF",
      "500": "#005794",
      "600": "#00407A",
      "700": "#002B61"
    },
    "amber": {
      "50": "#FFC63D",
      "100": "#F4AB1A",
      "200": "#D59000",
      "300": "#B67700",
      "400": "#985E00",
      "500": "#7B4600",
      "600": "#612F00",
      "700": "#4B1900"
    },
    "violet": {
      "50": "#F6BCFF",
      "100": "#D8A0FF",
      "200": "#BC85F4",
      "300": "#9F6BD7",
      "400": "#8452BB",
      "500": "#693A9F",
      "600": "#4E2185",
      "700": "#33076B"
    },
    "green": {
      "50": "#8CE990",
      "100": "#70CD76",
      "200": "#54B15C",
      "300": "#379644",
      "400": "#127B2C",
      "500": "#006213",
      "600": "#004900",
      "700": "#003100"
    },
    "red": {
      "50": "#FFA895",
      "100": "#FF8C7B",
      "200": "#FF7062",
      "300": "#E1554A",
      "400": "#C13933",
      "500": "#A2191D",
      "600": "#840006",
      "700": "#670000"
    },
    "rose": {
      "50": "#FFBAE9",
      "100": "#F49ECD",
      "200": "#D783B2",
      "300": "#BB6997",
      "400": "#9F507D",
      "500": "#843764",
      "600": "#691D4C",
      "700": "#4F0035"
    },
    "russet": {
      "50": "#FDCAA3",
      "100": "#E0AF89",
      "200": "#C3946F",
      "300": "#A77A56",
      "400": "#8B623F",
      "500": "#714A28",
      "600": "#563313",
      "700": "#3E1E00"
    }
  },
  "structural": {
    "background": "#FFFFFF",
    "bg_subtle": "#F6F7F9",
    "bg_highlight": "#D9EAFF",
    "border": "#E5E5E5",
    "gridline": "#F0F0F0",
    "axis_stroke": "#999999",
    "text_heading": "#1A1A2E",
    "text_body": "#4A4A4A",
    "text_muted": "#6D6D6D",
    "text_axis": "#666666",
    "annotation_dim": "#BBBBBB",
    "mark_black": "#000000",
    "tooltip_bg": "rgba(20,20,40,0.65)"
  },
  "brand": {
    "navy": "#101F5B",
    "blue": "#0072B2",
    "sky": "#63AAFF"
  },
  "aliases": {
    "purple": "violet",
    "pink": "rose",
    "yellow": "amber",
    "brown": "russet"
  }
} as const;
export type Tokens = typeof tokens;
