// GENERATED by scripts/sync-theme.mjs from the Style-Guide palette/colors.json.
// Do not edit by hand — run `npm run sync-theme`.

export const tokens = {
  "_version": "0.2.0",
  "_sources": [
    "Code Tests/shared/theme-v1.js",
    "app/R/blsmm_theme.R"
  ],
  "_naming_aliases": {
    "_note": "Users may refer to colors by common alternate names. Map these to the canonical names before resolving palette tokens.",
    "purple": "violet",
    "pink": "rose",
    "yellow": "amber",
    "brown": "russet"
  },
  "brand": {
    "navy": {
      "hex": "#101F5B",
      "role": "Primary brand color. Headings, primary buttons, UI accents."
    },
    "blue": {
      "hex": "#0072B2",
      "role": "Links, primary/baseline data series, interactive highlights. Same as cat1_blue."
    },
    "sky": {
      "hex": "#63AAFF",
      "role": "Light blue brand accent — used in logo and brand UI."
    }
  },
  "categorical": {
    "_note": "7-color palette for unrelated data series. Apply in order. Hue + luminance gaps are tuned for CVD (protan/deutan) safety; verified against Okabe-Ito (2008) reference. Aliases: see _naming_aliases at the top of this file.",
    "cat1_blue": {
      "hex": "#0072B2",
      "name": "Blue",
      "position": 1
    },
    "cat2_amber": {
      "hex": "#E69F00",
      "name": "Amber",
      "position": 2,
      "aliases": [
        "yellow"
      ]
    },
    "cat3_violet": {
      "hex": "#8856BF",
      "name": "Violet",
      "position": 3,
      "aliases": [
        "purple"
      ]
    },
    "cat4_green": {
      "hex": "#2A8B3A",
      "name": "Green",
      "position": 4
    },
    "cat5_red": {
      "hex": "#B8302C",
      "name": "Red",
      "position": 5
    },
    "cat6_rose": {
      "hex": "#CC79A7",
      "name": "Rose",
      "position": 6,
      "aliases": [
        "pink"
      ]
    },
    "cat7_russet": {
      "hex": "#7A5230",
      "name": "Russet",
      "position": 7,
      "aliases": [
        "brown"
      ]
    }
  },
  "scales": {
    "_note": "Tonal scales — 8 tiers per categorical hue at fixed CIELAB L* values. Tier naming follows Tailwind convention (50 lightest → 700 darkest). Generated by holding hue and chroma at the base, varying L* through the locked tiers. Use lighter tiers (50–200) for fills, mid tiers (300–500) for strokes/marks, and dark tiers (600–700) for text or emphasis on dark backgrounds.",
    "_tier_lstars": {
      "50": 85,
      "100": 75,
      "200": 65,
      "300": 55,
      "400": 45,
      "500": 35,
      "600": 25,
      "700": 15
    },
    "blue": {
      "50": "#95DAFF",
      "100": "#77BEFF",
      "200": "#58A3E7",
      "300": "#3689CB",
      "400": "#0070AF",
      "500": "#005794",
      "600": "#00407A",
      "700": "#002B61"
    },
    "amber": {
      "50": "#FFC63D",
      "100": "#F4AB1A",
      "200": "#D59000",
      "300": "#B67700",
      "400": "#985E00",
      "500": "#7B4600",
      "600": "#612F00",
      "700": "#4B1900"
    },
    "violet": {
      "50": "#F6BCFF",
      "100": "#D8A0FF",
      "200": "#BC85F4",
      "300": "#9F6BD7",
      "400": "#8452BB",
      "500": "#693A9F",
      "600": "#4E2185",
      "700": "#33076B"
    },
    "green": {
      "50": "#8CE990",
      "100": "#70CD76",
      "200": "#54B15C",
      "300": "#379644",
      "400": "#127B2C",
      "500": "#006213",
      "600": "#004900",
      "700": "#003100"
    },
    "red": {
      "50": "#FFA895",
      "100": "#FF8C7B",
      "200": "#FF7062",
      "300": "#E1554A",
      "400": "#C13933",
      "500": "#A2191D",
      "600": "#840006",
      "700": "#670000"
    },
    "rose": {
      "50": "#FFBAE9",
      "100": "#F49ECD",
      "200": "#D783B2",
      "300": "#BB6997",
      "400": "#9F507D",
      "500": "#843764",
      "600": "#691D4C",
      "700": "#4F0035"
    },
    "russet": {
      "50": "#FDCAA3",
      "100": "#E0AF89",
      "200": "#C3946F",
      "300": "#A77A56",
      "400": "#8B623F",
      "500": "#714A28",
      "600": "#563313",
      "700": "#3E1E00"
    }
  },
  "structural": {
    "_note": "Non-data UI and layout colors. Do not use for encoding data values.",
    "background": {
      "hex": "#FFFFFF"
    },
    "bg_subtle": {
      "hex": "#F6F7F9",
      "role": "Sidebar backgrounds, alternating table rows"
    },
    "bg_highlight": {
      "hex": "#D9EAFF",
      "role": "Read-only callout rows, soft highlights"
    },
    "border": {
      "hex": "#E5E5E5"
    },
    "gridline": {
      "hex": "#F0F0F0",
      "role": "Standard horizontal gridlines (0.75 px)."
    },
    "axis_stroke": {
      "hex": "#999999",
      "role": "The y=0 baseline gridline (1 px). Applies whenever 0 — or the equivalent index baseline (e.g. 100 on a rebased index) — appears in the chart's y-range, whether at the bottom of the plot or somewhere in the middle."
    },
    "text_heading": {
      "hex": "#1A1A2E"
    },
    "text_body": {
      "hex": "#4A4A4A"
    },
    "text_muted": {
      "hex": "#6D6D6D",
      "role": "Axis labels, secondary annotations"
    },
    "text_axis": {
      "hex": "#666666"
    },
    "annotation_dim": {
      "hex": "#BBBBBB",
      "role": "Subtle reference lines, suppressed labels"
    },
    "mark_black": {
      "hex": "#000000",
      "role": "Pure black for neutral/baseline chart marks — e.g. a 'national average' line, a 'total' line, a reference threshold. Use sparingly; strong visual weight that should signal 'this is the reference.' Distinct from text colors (text_heading, etc.) which are tuned for typography on white."
    },
    "tooltip_bg": {
      "rgba": "rgba(20,20,40,0.65)"
    }
  },
  "logo": {
    "_note": "Logo always uses one of two pairings: navy + sky (on light backgrounds) OR knockout-white + sky (on dark backgrounds). The accent stripe is always brand.sky.",
    "mark_primary": {
      "hex": "#101F5B",
      "role": "Logo text on light backgrounds (same as brand.navy)"
    },
    "mark_accent": {
      "hex": "#63AAFF",
      "role": "Logo accent stripe (same as brand.sky). Used in both light and KO variants."
    },
    "mark_knockout": {
      "hex": "#FFFFFF",
      "role": "Logo text on dark backgrounds"
    }
  }
} as const;
export type Tokens = typeof tokens;
