#!/usr/bin/env node
/**
 * gen-assets.mjs — Embed the TBL logo SVG and Figtree font as base64 data URLs
 * and write src/embed/assets.ts with the exported constants.
 *
 * Run with: node scripts/gen-assets.mjs
 */

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");

// Source paths — the logo lives in the vendored style-guide/ assets (logos + palette only).
const LOGO_PATH = resolve(ROOT, "style-guide/logos/primary/TBL_ID_Graph_Primary.svg");
const FONT_PATH = resolve(ROOT, "src/embed/assets/Figtree-variable.ttf");
const OUT_PATH = resolve(ROOT, "src/embed/assets.ts");

// Extract viewBox width and height from an SVG string.
// Returns { w: number, h: number } or throws if not found.
function extractViewBox(svg) {
  const m = svg.match(/viewBox=["']([^"']+)["']/);
  if (!m) throw new Error("No viewBox found in SVG");
  const parts = m[1].trim().split(/[\s,]+/);
  if (parts.length < 4) throw new Error(`Unexpected viewBox: ${m[1]}`);
  const w = parseFloat(parts[2]);
  const h = parseFloat(parts[3]);
  if (!Number.isFinite(w) || !Number.isFinite(h) || h === 0) {
    throw new Error(`Invalid viewBox dimensions: w=${w} h=${h}`);
  }
  return { w, h };
}

async function main() {
  console.log("Reading logo SVG...");
  const logoSvg = await readFile(LOGO_PATH, "utf8");
  const { w, h } = extractViewBox(logoSvg);
  const logoAspect = w / h;
  console.log(`  viewBox: ${w}x${h}  -> LOGO_ASPECT = ${logoAspect.toFixed(6)}`);

  const logoB64 = Buffer.from(new TextEncoder().encode(logoSvg)).toString("base64");
  const logoDataUrl = `data:image/svg+xml;base64,${logoB64}`;

  console.log("Reading Figtree font...");
  const fontBuf = await readFile(FONT_PATH);
  const fontB64 = fontBuf.toString("base64");
  const figtreeFontFace =
    `@font-face{font-family:'Figtree';` +
    `src:url(data:font/ttf;base64,${fontB64}) format('truetype');` +
    `font-weight:300 900;font-style:normal;}`;

  const ts = `// AUTO-GENERATED by scripts/gen-assets.mjs — do not edit by hand.
// Re-run \`npm run gen-assets\` after updating the logo or font.

/** Raw SVG markup for the TBL primary graph logo. */
export const LOGO_SVG: string = ${JSON.stringify(logoSvg)};

/** Data URL (base64) for the TBL primary graph logo, for use as <image href>. */
export const LOGO_DATA_URL: string = ${JSON.stringify(logoDataUrl)};

/** @font-face rule embedding Figtree variable font as a base64 data URL. */
export const FIGTREE_FONT_FACE: string = ${JSON.stringify(figtreeFontFace)};

/** Logo width / height ratio (extracted from the SVG viewBox). */
export const LOGO_ASPECT: number = ${logoAspect};
`;

  await mkdir(dirname(OUT_PATH), { recursive: true });
  await writeFile(OUT_PATH, ts, "utf8");
  console.log(`Written: ${OUT_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
