// sync-theme: generate src/theme/tokens.ts from the Style-Guide's palette/colors.json.
//
// The Style-Guide repo is the SINGLE SOURCE OF TRUTH for the palette. This script
// reads it (from the `style-guide/` git submodule, or a path passed as argv[2]) and
// emits a committed, typed tokens module the engine imports. CI re-runs this and
// fails if the committed tokens.ts is stale vs. the submodule.
//
// Usage: node scripts/sync-theme.mjs [path-to-colors.json]
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";

const repoRoot = new URL("..", import.meta.url);
const defaultColors = fileURLToPath(new URL("style-guide/palette/colors.json", repoRoot));
const colorsPath = process.argv[2] ?? defaultColors;

if (!existsSync(colorsPath)) {
  console.error(
    `sync-theme: colors.json not found at ${colorsPath}\n` +
      `Add the Style-Guide submodule (git submodule add … style-guide) or pass a path.`,
  );
  process.exit(1);
}

const colors = JSON.parse(readFileSync(colorsPath, "utf8"));
const outPath = fileURLToPath(new URL("src/theme/tokens.ts", repoRoot));

// NOTE: the exact shape of colors.json is mapped here once the Style-Guide submodule
// is wired. For scaffolding we emit a typed pass-through of the parsed JSON so the
// module compiles; the real categorical/scales/structural mapping lands with the
// theme port (engine step 2).
const banner =
  "// GENERATED by scripts/sync-theme.mjs from the Style-Guide palette/colors.json.\n" +
  "// Do not edit by hand — run `npm run sync-theme`.\n";

const body =
  `export const tokens = ${JSON.stringify(colors, null, 2)} as const;\n` +
  `export type Tokens = typeof tokens;\n`;

writeFileSync(outPath, banner + "\n" + body, "utf8");
console.log(`sync-theme: wrote ${outPath}`);
