// sync-theme: generate src/theme/tokens.ts from the Style-Guide's palette/colors.json.
//
// The Style-Guide repo is the SINGLE SOURCE OF TRUTH for the palette. This script
// reads it (from the `style-guide/` git submodule, or a path passed as argv[2]) and
// emits a committed, typed tokens module the engine imports. CI re-runs this and
// fails if the committed tokens.ts is stale vs. the submodule.
//
// The emitted module normalizes colors.json into three flat maps the engine consumes
// directly — `categorical[]`, `scales`, `structural` — plus `brand` and `aliases`.
// The categorical LIGHT tier (chart slots 8-14) is DERIVED here from `scales`, not
// hand-maintained: each cat's base hex is matched to the nearest tier in its own
// tonal scale, then stepped two tiers lighter. This reproduces the tracker's old
// hand-listed light palette exactly while keeping colors.json the only source.
//
// Usage: node scripts/sync-theme.mjs [path-to-colors.json]
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";

const repoRoot = new URL("..", import.meta.url);
const defaultColors = fileURLToPath(new URL("style-guide/palette/colors.json", repoRoot));
const colorsPath = process.argv[2] ?? defaultColors;

if (!existsSync(colorsPath)) {
  console.error(
    `sync-theme: colors.json not found at ${colorsPath}\n` +
      `Add the Style-Guide submodule (git submodule add … style-guide) or pass a path.`,
  );
  process.exit(1);
}

const colors = JSON.parse(readFileSync(colorsPath, "utf8"));

// The Style-Guide also ships palette/colors.css — the canonical `:root` block of
// `--tbl-*` CSS custom properties (brand, categorical, tonal scales, structural, text).
// We emit it verbatim as TOKENS_CSS so the engine's HTML/CSS output uses the EXACT same
// color values as the SVG side (and the tracker), instead of hand-written approximations.
const cssPath = colorsPath.replace(/colors\.json$/, "colors.css");
let tokensCss = "";
if (existsSync(cssPath)) {
  const cssText = readFileSync(cssPath, "utf8");
  const rootMatch = /:root\s*\{[^}]*\}/.exec(cssText);
  if (!rootMatch) {
    console.error(`sync-theme: no :root block found in ${cssPath}`);
    process.exit(1);
  }
  tokensCss = rootMatch[0];
} else {
  console.error(`sync-theme: colors.css not found at ${cssPath} (needed for CSS tokens)`);
  process.exit(1);
}
const outPath = fileURLToPath(new URL("src/theme/tokens.ts", repoRoot));

// Tier ladder, lightest → darkest (Tailwind convention). The light tier is two
// steps lighter than the base's nearest tier.
const TIER_LADDER = ["50", "100", "200", "300", "400", "500", "600", "700"];
const LIGHT_STEP = 2;

const hexToRgb = (hex) => {
  const h = hex.replace("#", "");
  return [parseInt(h.slice(0, 2), 16), parseInt(h.slice(2, 4), 16), parseInt(h.slice(4, 6), 16)];
};
const rgbDist2 = (a, b) => (a[0] - b[0]) ** 2 + (a[1] - b[1]) ** 2 + (a[2] - b[2]) ** 2;

// Nearest tier (by RGB distance) of `baseHex` within its own tonal `scale`.
const nearestTierIndex = (baseHex, scale) => {
  const base = hexToRgb(baseHex);
  let bestIdx = 0;
  let bestDist = Infinity;
  TIER_LADDER.forEach((tier, i) => {
    const d = rgbDist2(base, hexToRgb(scale[tier]));
    if (d < bestDist) { bestDist = d; bestIdx = i; }
  });
  return bestIdx;
};

const dropMeta = (obj) =>
  Object.fromEntries(Object.entries(obj).filter(([k]) => !k.startsWith("_")));

// scales: hue → { tier: hex }, meta keys stripped.
const scales = {};
for (const [hue, tiers] of Object.entries(dropMeta(colors.scales))) {
  scales[hue] = dropMeta(tiers);
}

// categorical[]: ordered by `position`, with base + derived light tier.
const categorical = Object.entries(dropMeta(colors.categorical))
  .map(([catKey, v]) => {
    const hue = catKey.replace(/^cat\d+_/, ""); // cat1_blue → blue
    const scale = scales[hue];
    if (!scale) throw new Error(`sync-theme: no tonal scale for categorical hue "${hue}"`);
    const baseIdx = nearestTierIndex(v.hex, scale);
    const lightIdx = Math.max(0, baseIdx - LIGHT_STEP);
    return {
      key: hue,
      name: v.name,
      position: v.position,
      base: v.hex,
      light: scale[TIER_LADDER[lightIdx]],
    };
  })
  .sort((a, b) => a.position - b.position);

// structural: name → color string (hex or rgba), meta keys stripped.
const structural = {};
for (const [name, v] of Object.entries(dropMeta(colors.structural))) {
  structural[name] = v.hex ?? v.rgba;
}

// brand: name → hex.
const brand = {};
for (const [name, v] of Object.entries(dropMeta(colors.brand))) {
  brand[name] = v.hex;
}

const aliases = dropMeta(colors._naming_aliases ?? {});

const tokens = {
  version: colors._version,
  categorical,
  scales,
  structural,
  brand,
  aliases,
};

const banner =
  "// GENERATED by scripts/sync-theme.mjs from the Style-Guide palette/colors.json.\n" +
  "// Do not edit by hand — run `npm run sync-theme`.\n";

const body =
  `export const tokens = ${JSON.stringify(tokens, null, 2)} as const;\n` +
  `export type Tokens = typeof tokens;\n\n` +
  `// The Style-Guide's canonical \`:root\` block of --tbl-* CSS custom properties, emitted\n` +
  `// verbatim from palette/colors.css. The engine's CSS/HTML output prepends this so its\n` +
  `// colors match the SVG side and the tracker exactly.\n` +
  `export const TOKENS_CSS = ${JSON.stringify(tokensCss)};\n`;

writeFileSync(outPath, banner + "\n" + body, "utf8");
console.log(`sync-theme: wrote ${outPath}`);
